// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using TravelDisruptionAgent.Api.Infrastructure.Data;

#nullable disable

namespace TravelDisruptionAgent.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.AlertAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<DateOnly>("AcknowledgedDate")
                        .HasColumnType("date")
                        .HasColumnName("acknowledged_date");

                    b.Property<string>("AlertKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alert_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_alert_acknowledgements");

                    b.HasIndex("AlertKey", "AcknowledgedDate")
                        .IsUnique()
                        .HasDatabaseName("ix_alert_acknowledgements_alert_key_acknowledged_date");

                    b.ToTable("alert_acknowledgements", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.AlternateOfferAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.HasKey("Id")
                        .HasName("pk_alternate_offer_audits");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_alternate_offer_audits_case_id");

                    b.ToTable("alternate_offer_audits", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.BadCaseLearning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DraftMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("draft_markdown");

                    b.Property<string>("EvaluationNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evaluation_note");

                    b.Property<Guid>("EvaluatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluator_user_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("RagDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("rag_document_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bad_case_learnings");

                    b.HasIndex("EvaluatorUserId")
                        .HasDatabaseName("ix_bad_case_learnings_evaluator_user_id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_bad_case_learnings_message_id");

                    b.HasIndex("RagDocumentId")
                        .HasDatabaseName("ix_bad_case_learnings_rag_document_id");

                    b.ToTable("bad_case_learnings", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<string>("ConfirmationNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confirmation_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("GuestUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_user_id");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("integer")
                        .HasColumnName("guests_count");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("ConfirmationNo")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_confirmation_no");

                    b.HasIndex("GuestUserId")
                        .HasDatabaseName("ix_bookings_guest_user_id");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_bookings_hotel_id");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("ix_bookings_room_type_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Call", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("CalleeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("callee_type");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("EndedReason")
                        .HasColumnType("text")
                        .HasColumnName("ended_reason");

                    b.Property<Guid>("InitiatedByCoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_coordinator_id");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_calls");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_calls_case_id");

                    b.HasIndex("InitiatedByCoordinatorId")
                        .HasDatabaseName("ix_calls_initiated_by_coordinator_id");

                    b.HasIndex("ReceiverUserId")
                        .HasDatabaseName("ix_calls_receiver_user_id");

                    b.ToTable("calls", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CallRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uuid")
                        .HasColumnName("call_id");

                    b.Property<string>("CoordinatorNote")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("InsightsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("insights_json");

                    b.Property<int?>("AuditRating")
                        .HasColumnType("integer")
                        .HasColumnName("audit_rating");

                    b.Property<string>("AuditComment")
                        .HasColumnType("text")
                        .HasColumnName("audit_comment");

                    b.Property<DateTimeOffset?>("AuditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("audited_at");

                    b.Property<Guid?>("AuditedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("audited_by_user_id");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processing_status");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("boolean")
                        .HasColumnName("reviewed");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("text")
                        .HasColumnName("transcript_text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_call_recordings");

                    b.HasIndex("CallId")
                        .IsUnique()
                        .HasDatabaseName("ix_call_recordings_call_id");

                    b.ToTable("call_recordings", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeCoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_coordinator_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("CloseReason")
                        .HasColumnType("text")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisruptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("disruption_id");

                    b.Property<string>("EscalationReason")
                        .HasColumnType("text")
                        .HasColumnName("escalation_reason");

                    b.Property<string>("EscalationReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("escalation_review_note");

                    b.Property<bool?>("EscalationReviewedAsReasonable")
                        .HasColumnType("boolean")
                        .HasColumnName("escalation_reviewed_as_reasonable");

                    b.Property<DateTimeOffset?>("EscalationReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalation_reviewed_at");

                    b.Property<Guid?>("EscalationReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("escalation_reviewed_by_user_id");

                    b.Property<string>("EscalationTrigger")
                        .HasColumnType("text")
                        .HasColumnName("escalation_trigger");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text")
                        .HasColumnName("result_summary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("AssigneeCoordinatorId")
                        .HasDatabaseName("ix_cases_assignee_coordinator_id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_cases_booking_id");

                    b.HasIndex("DisruptionId")
                        .HasDatabaseName("ix_cases_disruption_id");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CaseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FromCoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_coordinator_id");

                    b.Property<Guid>("ToCoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_coordinator_id");

                    b.HasKey("Id")
                        .HasName("pk_case_assignments");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_assignments_case_id");

                    b.ToTable("case_assignments", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CaseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_case_notes");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_case_notes_author_user_id");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_notes_case_id");

                    b.ToTable("case_notes", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CaseWorkflowStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_case_workflow_state_histories");

                    b.HasIndex("CaseId", "StartedAt")
                        .HasDatabaseName("ix_case_workflow_state_histories_case_id_started_at");

                    b.HasIndex("State", "StartedAt", "EndedAt")
                        .HasDatabaseName("ix_case_workflow_state_histories_state_started_at_ended_at");

                    b.ToTable("case_workflow_state_histories", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CustomTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("OwnerRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_role");

                    b.HasKey("Id")
                        .HasName("pk_custom_tags");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_custom_tags_hotel_id");

                    b.HasIndex("OwnerRole", "HotelId")
                        .HasDatabaseName("ix_custom_tags_owner_role_hotel_id");

                    b.ToTable("custom_tags", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpoPushToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expo_push_token");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_tokens");

                    b.HasIndex("ExpoPushToken")
                        .IsUnique()
                        .HasDatabaseName("ix_device_tokens_expo_push_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_tokens_user_id");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Disruption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeCoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_coordinator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndAtOrWindow")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_or_window");

                    b.Property<string>("EventSubtype")
                        .HasColumnType("text")
                        .HasColumnName("event_subtype");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<double?>("RadiusKm")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_km");

                    b.Property<string>("RawSignalJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_signal_json");

                    b.Property<string>("RawSignalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_signal_text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_disruptions");

                    b.ToTable("disruptions", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.DisruptionExclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisruptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("disruption_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_disruption_exclusions");

                    b.HasIndex("DisruptionId", "BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_disruption_exclusions_disruption_id_booking_id");

                    b.ToTable("disruption_exclusions", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.DisruptionWindowAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DisruptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("disruption_id");

                    b.Property<DateTimeOffset?>("NewEndAtOrWindow")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_end_at_or_window");

                    b.Property<DateTimeOffset>("NewStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_start_at");

                    b.Property<DateTimeOffset?>("OldEndAtOrWindow")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("old_end_at_or_window");

                    b.Property<DateTimeOffset>("OldStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("old_start_at");

                    b.HasKey("Id")
                        .HasName("pk_disruption_window_audits");

                    b.HasIndex("DisruptionId")
                        .HasDatabaseName("ix_disruption_window_audits_disruption_id");

                    b.ToTable("disruption_window_audits", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.FaqQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AskCount")
                        .HasColumnType("integer")
                        .HasColumnName("ask_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("LastAskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_asked_at");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_faq_questions");

                    b.ToTable("faq_questions", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GoldenTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Expect")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expect");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_golden_tests");

                    b.ToTable("golden_tests", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GoldenTestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer")
                        .HasColumnName("fail_count");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer")
                        .HasColumnName("pass_count");

                    b.Property<string>("TriggerDocumentName")
                        .HasColumnType("text")
                        .HasColumnName("trigger_document_name");

                    b.Property<int?>("TriggerVersion")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_version");

                    b.HasKey("Id")
                        .HasName("pk_golden_test_runs");

                    b.ToTable("golden_test_runs", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GoldenTestRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actual")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actual");

                    b.Property<string>("Expect")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expect");

                    b.Property<Guid>("GoldenTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("golden_test_id");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_golden_test_run_items");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_golden_test_run_items_run_id");

                    b.ToTable("golden_test_run_items", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GuestCustomTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("AppliedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by_user_id");

                    b.Property<Guid>("CustomTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_tag_id");

                    b.Property<Guid>("GuestUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_user_id");

                    b.HasKey("Id")
                        .HasName("pk_guest_custom_tags");

                    b.HasIndex("GuestUserId")
                        .HasDatabaseName("ix_guest_custom_tags_guest_user_id");

                    b.HasIndex("CustomTagId", "GuestUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_custom_tags_custom_tag_id_guest_user_id");

                    b.ToTable("guest_custom_tags", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("text")
                        .HasColumnName("google_place_id");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PrimaryImageIndex")
                        .HasColumnType("integer")
                        .HasColumnName("primary_image_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hotels");

                    b.ToTable("hotels", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.HotelPerk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_hotel_perks");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_hotel_perks_hotel_id");

                    b.ToTable("hotel_perks", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.HotelRefundPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SourceFileKey")
                        .HasColumnType("text")
                        .HasColumnName("source_file_key");

                    b.Property<string>("SourceFileName")
                        .HasColumnType("text")
                        .HasColumnName("source_file_name");

                    b.Property<string>("StructuredRulesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_rules");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hotel_refund_policies");

                    b.HasIndex("HotelId", "IsActive")
                        .HasDatabaseName("ix_hotel_refund_policies_hotel_id_is_active");

                    b.ToTable("hotel_refund_policies", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inquiries");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_inquiries_case_id");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_inquiries_hotel_id");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentJson")
                        .HasColumnType("text")
                        .HasColumnName("attachment_json");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Escalated")
                        .HasColumnType("boolean")
                        .HasColumnName("escalated");

                    b.Property<bool?>("MissedEscalationConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("missed_escalation_confirmed");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_role");

                    b.Property<string>("Thread")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thread");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vote")
                        .HasColumnType("text")
                        .HasColumnName("vote");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_messages_case_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_notifications_case_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("availability");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<bool?>("CoordinatorVisibilityOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("coordinator_visibility_override");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomTitle")
                        .HasColumnType("text")
                        .HasColumnName("custom_title");

                    b.Property<DateTimeOffset?>("ExecutionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_requested_at");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.PrimitiveCollection<List<string>>("PerkNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("perk_names");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean")
                        .HasColumnName("selected");

                    b.Property<string>("UnavailableReason")
                        .HasColumnType("text")
                        .HasColumnName("unavailable_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_options");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_options_case_id");

                    b.ToTable("options", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.OptionLockAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_option_lock_audits");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("ix_option_lock_audits_option_id");

                    b.ToTable("option_lock_audits", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RagDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<bool>("IsDefaultVersion")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_rag_documents");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_rag_documents_hotel_id");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_rag_documents_name_version");

                    b.ToTable("rag_documents", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RagDocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("RagDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("rag_document_id");

                    b.HasKey("Id")
                        .HasName("pk_rag_document_chunks");

                    b.HasIndex("RagDocumentId")
                        .HasDatabaseName("ix_rag_document_chunks_rag_document_id");

                    b.ToTable("rag_document_chunks", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RefundConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("ConfirmedByCoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_coordinator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_refund_confirmations");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_refund_confirmations_case_id");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("ix_refund_confirmations_option_id");

                    b.ToTable("refund_confirmations", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("amenities");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("price_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_room_types");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_room_types_hotel_id");

                    b.ToTable("room_types", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FaqProcessedThrough")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("faq_processed_through");

                    b.Property<bool>("FrustrationEscalationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("frustration_escalation_enabled");

                    b.Property<bool>("LowConfidenceEscalationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("low_confidence_escalation_enabled");

                    b.Property<int>("UnresolvedTurnThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("unresolved_turn_threshold");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<bool>("KeepMessagesSimple")
                        .HasColumnType("boolean")
                        .HasColumnName("keep_messages_simple");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<bool>("SpeakSlowly")
                        .HasColumnType("boolean")
                        .HasColumnName("speak_slowly");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StayPreference")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("stay_preference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_users_hotel_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.UserDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_document_versions");

                    b.HasIndex("UserId", "DocumentName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_document_versions_user_id_document_name");

                    b.ToTable("user_document_versions", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.UserStatusAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_status_audits");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_status_audits_user_id");

                    b.ToTable("user_status_audits", (string)null);
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.BadCaseLearning", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bad_case_learnings_users_evaluator_user_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bad_case_learnings_messages_message_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RagDocument", "RagDocument")
                        .WithMany()
                        .HasForeignKey("RagDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bad_case_learnings_rag_documents_rag_document_id");

                    b.Navigation("Evaluator");

                    b.Navigation("Message");

                    b.Navigation("RagDocument");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Booking", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.User", "GuestUser")
                        .WithMany()
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_guest_user_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_hotels_hotel_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_room_types_room_type_id");

                    b.Navigation("GuestUser");

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Call", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calls_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CallRecording", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Call", "Call")
                        .WithOne("Recording")
                        .HasForeignKey("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CallRecording", "CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_call_recordings_calls_call_id");

                    b.Navigation("Call");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cases_bookings_booking_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Disruption", "Disruption")
                        .WithMany()
                        .HasForeignKey("DisruptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cases_disruptions_disruption_id");

                    b.Navigation("Booking");

                    b.Navigation("Disruption");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CaseAssignment", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_assignments_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CaseNote", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_case_notes_users_author_user_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_notes_cases_case_id");

                    b.Navigation("Author");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CaseWorkflowStateHistory", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_workflow_state_histories_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CustomTag", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .HasConstraintName("fk_custom_tags_hotels_hotel_id");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.DeviceToken", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GoldenTestRunItem", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GoldenTestRun", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_golden_test_run_items_golden_test_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GuestCustomTag", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.CustomTag", "CustomTag")
                        .WithMany()
                        .HasForeignKey("CustomTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_custom_tags_custom_tags_custom_tag_id");

                    b.Navigation("CustomTag");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.HotelPerk", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotel_perks_hotels_hotel_id");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.HotelRefundPolicy", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotel_refund_policies_hotels_hotel_id");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Inquiry", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inquiries_cases_case_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inquiries_hotels_hotel_id");

                    b.Navigation("Case");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Message", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany("Messages")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Notification", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_cases_case_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Option", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_options_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RagDocument", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_rag_documents_hotels_hotel_id");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RagDocumentChunk", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RagDocument", "RagDocument")
                        .WithMany("Chunks")
                        .HasForeignKey("RagDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rag_document_chunks_rag_documents_rag_document_id");

                    b.Navigation("RagDocument");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RefundConfirmation", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refund_confirmations_cases_case_id");

                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refund_confirmations_options_option_id");

                    b.Navigation("Case");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RoomType", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_types_hotels_hotel_id");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.User", b =>
                {
                    b.HasOne("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_hotels_hotel_id");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Call", b =>
                {
                    b.Navigation("Recording");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Case", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.GoldenTestRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.Hotel", b =>
                {
                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("TravelDisruptionAgent.Api.Infrastructure.Data.Entities.RagDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
